version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    env_file:
      - .env.mssql.local
    ports:
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql

volumes:
  mssql:
    driver: local
